name: hotronguoikhiemthi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3 # sử dụng camera  
  vibration: ^3.1.3 # điều khiển rung thiết bị
  speech_to_text: ^7.3.0  # chuyển văn bản thành giọng nói
  provider: ^6.0.0          # Quản lý trạng thái
  permission_handler: ^11.0.0 # Quản lý quyền Camera/Micro
  flutter_tts: ^3.8.0       # Để thông báo trạng thái bằng giọng nói

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
